server:
  port: 8089
spring:
  application:
    name: demo-consumer
  datasource:
    url: jdbc:postgresql://localhost:50763/factory
    username: factory
    password: factory
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: demo-consumer-group
    admin:
      auto-create: true

factory:
  api:
    base-url: http://localhost:48763
